name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Test setup for multiple versions.
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24','1.25','1.26']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Run tests
        run: go test ./... -v -race
  
  # Linter setup
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: latest

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.26'

  # Coverage setup
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true

      - name: Run tests
        run: go test ./... -v -race -covermode=atomic -coverprofile=coverage.out

      - name: Check coverage
        uses: vladopajic/go-test-coverage@v2.18.3
        with:
          config: ./.testcoverage.yml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out